# Generated by Django 4.1.7 on 2023-03-13 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Countries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iso",
                    models.CharField(
                        max_length=5,
                        unique=True,
                        verbose_name="ISO 3166-1 alpha-2 code of the country",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="common country name"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(null=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(null=True, verbose_name="deleted at"),
                ),
            ],
            options={
                "verbose_name": "country",
                "verbose_name_plural": "countries",
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acronym",
                    models.CharField(
                        max_length=10, verbose_name="document type acronym"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="name of document type"
                    ),
                ),
                (
                    "country",
                    models.ManyToManyField(
                        related_name="document_type_country",
                        to="config.countries",
                        verbose_name="country",
                    ),
                ),
            ],
            options={
                "verbose_name": "document type",
                "verbose_name_plural": "document types",
            },
        ),
        migrations.CreateModel(
            name="Districts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iso",
                    models.CharField(
                        max_length=5,
                        unique=True,
                        verbose_name="ISO 3166-2 of administrative subdivision",
                    ),
                ),
                (
                    "zipcode",
                    models.CharField(
                        max_length=25,
                        unique=True,
                        verbose_name="administrative subdivision zip code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        verbose_name="common name of the administrative subdivision",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(null=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(null=True, verbose_name="deleted at"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="country_district",
                        to="config.countries",
                        verbose_name="country",
                    ),
                ),
            ],
            options={
                "verbose_name": "district",
                "verbose_name_plural": "districts",
            },
        ),
        migrations.CreateModel(
            name="Currencies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iso",
                    models.CharField(
                        max_length=5,
                        unique=True,
                        verbose_name="ISO 4217 of a country's currency",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="name of the currency"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(null=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(null=True, verbose_name="deleted at"),
                ),
                (
                    "country",
                    models.ManyToManyField(
                        related_name="currency_country",
                        to="config.countries",
                        verbose_name="country",
                    ),
                ),
            ],
            options={
                "verbose_name": "currency",
                "verbose_name_plural": "currencies",
            },
        ),
        migrations.CreateModel(
            name="Cities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zipcode",
                    models.CharField(
                        max_length=25, unique=True, verbose_name="city zip code"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="common name of the city"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(null=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(null=True, verbose_name="deleted at"),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="city_district",
                        to="config.districts",
                        verbose_name="district",
                    ),
                ),
            ],
            options={
                "verbose_name": "city",
                "verbose_name_plural": "cities",
            },
        ),
    ]
