version: '3.9'
services:
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./jobboard:/code
      - web-django:/usr/src/app
      - web-static:/usr/src/app/static
    ports:
      - "3000:8000"
    env_file: .env
    # environment:
    #   DEBUG: 'false'
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=db_job
      - POSTGRES_USER=adminpg
      - POSTGRES_PASSWORD=proygrado@2023
    volumes:
      - pgdata:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "adminpg@2023"
    ports:
      - "80:80"
    depends_on:
      - postgres

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
volumes:
  web-django:
  web-static:
  pgdata:
  redisdata: