# Generated by Django 4.1.7 on 2023-03-16 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("config", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(null=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(null=True, verbose_name="deleted at"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="country_contract_type",
                        to="config.countries",
                        verbose_name="country",
                    ),
                ),
            ],
            options={
                "verbose_name": "contract type",
                "verbose_name_plural": "contract types",
            },
        ),
        migrations.CreateModel(
            name="Modalities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, verbose_name="name")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="country_modality",
                        to="config.countries",
                        verbose_name="country",
                    ),
                ),
            ],
            options={
                "verbose_name": "modality",
                "verbose_name_plural": "modalities",
            },
        ),
        migrations.CreateModel(
            name="PayPeriods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, verbose_name="name")),
            ],
            options={
                "verbose_name": "pay period",
                "verbose_name_plural": "pay periods",
            },
        ),
        migrations.CreateModel(
            name="PostStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, verbose_name="name")),
            ],
            options={
                "verbose_name": "postulation status",
                "verbose_name_plural": "postulation statuses",
            },
        ),
        migrations.CreateModel(
            name="Requirements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
            ],
            options={
                "verbose_name": "requirement",
                "verbose_name_plural": "requirements",
            },
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=15, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
            },
        ),
        migrations.CreateModel(
            name="Workdays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
            ],
            options={
                "verbose_name": "workday",
                "verbose_name_plural": "workdays",
            },
        ),
        migrations.CreateModel(
            name="Offers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vacancies", models.IntegerField(blank=True, default=0, null=True)),
                ("hiring_date", models.DateField(null=True)),
                ("description", models.TextField(verbose_name="description")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(null=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(null=True, verbose_name="deleted at"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offer_city",
                        to="config.cities",
                        verbose_name="city",
                    ),
                ),
                (
                    "conttype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offer_contract_type",
                        to="offers.contracttypes",
                        verbose_name="contract type",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offer_currency",
                        to="config.currencies",
                        verbose_name="currency",
                    ),
                ),
                (
                    "modality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offer_modality",
                        to="offers.modalities",
                        verbose_name="modality",
                    ),
                ),
                (
                    "payperiod",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offer_payperiod",
                        to="offers.payperiods",
                        verbose_name="pay period",
                    ),
                ),
                (
                    "requirements",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="offers_requirements",
                        to="offers.requirements",
                        verbose_name="requirements",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="offers_tags",
                        to="offers.tags",
                        verbose_name="tags",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offer_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "workday",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offer_workday",
                        to="offers.workdays",
                        verbose_name="workday",
                    ),
                ),
            ],
            options={
                "verbose_name": "offer",
                "verbose_name_plural": "offers",
            },
        ),
        migrations.CreateModel(
            name="Candidatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(null=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(null=True, verbose_name="deleted at"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="candidate",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidature_offer",
                        to="offers.offers",
                        verbose_name="offer",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidature_status",
                        to="offers.poststatus",
                        verbose_name="status",
                    ),
                ),
            ],
            options={
                "verbose_name": "candidature",
                "verbose_name_plural": "candidatures",
            },
        ),
    ]
