# Generated by Django 4.1.7 on 2023-03-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offers",
            name="requirements",
            field=models.ManyToManyField(
                blank=True,
                related_name="offers_requirements",
                to="offers.requirements",
                verbose_name="requirements",
            ),
        ),
        migrations.AlterField(
            model_name="offers",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="offers_tags",
                to="offers.tags",
                verbose_name="tags",
            ),
        ),
    ]
