# Generated by Django 4.1.7 on 2023-03-16 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0002_alter_offers_requirements_alter_offers_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contracttypes",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="contracttypes",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="contracttypes",
            name="updated_at",
        ),
    ]
