# Generated by Django 4.1.7 on 2023-03-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_usergroups_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="roles",
            name="code",
            field=models.CharField(
                default="000", max_length=3, unique=True, verbose_name="role code"
            ),
            preserve_default=False,
        ),
    ]
