# Generated by Django 4.1.7 on 2023-03-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_roles_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apps",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="name"),
        ),
    ]
